import React, { useEffect, useState } from "react";

import { getMyReleasedResults } from "../../../api/examinations.api";
import Button from "../../../components/ui/Button";
import EmptyState from "../../../components/ui/EmptyState";
import Loader from "../../../components/ui/Loader";
import PageHeader from "../../../components/ui/PageHeader";

export default function MyReleasedResultsPage() {
  const institutionName =
    import.meta.env.VITE_INSTITUTION_NAME || "Demonstration University";
  const [records, setRecords] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const load = async () => {
      try {
        const data = await getMyReleasedResults();
        setRecords(data?.data?.records || []);
      } catch (err) {
        setError(err?.response?.data?.message || "Failed to load results");
      } finally {
        setLoading(false);
      }
    };
    load();
  }, []);

  if (loading) return <Loader text="Loading released results..." />;
  if (error) return <EmptyState title={error} />;

  return (
    <div>
      <div className="print-hide">
        <PageHeader
          title="My Results"
          subtitle="View and print results released by the Registrar."
        />
      </div>
      {records.length === 0 ? (
        <EmptyState title="No results have been released yet." />
      ) : (
        records.map((record) => (
          <section className="result-sheet" key={record._id}>
            <div className="result-sheet-header">
              <img src="/branding/uniportal-logo.svg" alt="UniPortal" />
              <div>
                <p>{institutionName}</p>
                <h1>Statement of Semester Results</h1>
                <span>UniPortal Institutional Result Sheet</span>
              </div>
            </div>
            <div className="result-student-grid">
              <p><strong>Student:</strong> {record.student?.name}</p>
              <p><strong>Registration No:</strong> {record.studentProfile?.registrationNumber || record.studentProfile?.studentId || "N/A"}</p>
              <p><strong>Faculty:</strong> {record.studentProfile?.faculty || "N/A"}</p>
              <p><strong>Department:</strong> {record.studentProfile?.department || "N/A"}</p>
              <p><strong>Program:</strong> {record.studentProfile?.program || "N/A"}</p>
              <p><strong>Academic Year:</strong> {record.academicYear}</p>
              <p><strong>Semester:</strong> Semester {record.semester}</p>
            </div>
            <div className="responsive-table">
              <table>
                <thead>
                  <tr>
                    <th>Code</th>
                    <th>Course Title</th>
                    <th>CH</th>
                    <th>Marks</th>
                    <th>Grade</th>
                    <th>GP</th>
                    <th>Result</th>
                  </tr>
                </thead>
                <tbody>
                  {(record.courses || []).map((course) => (
                    <tr key={course.course || course.code}>
                      <td>{course.code}</td>
                      <td>{course.title}</td>
                      <td>{course.creditHours}</td>
                      <td>{course.marks}</td>
                      <td>{course.grade}</td>
                      <td>{course.gradePoint}</td>
                      <td>{formatLabel(course.status)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <div className="result-summary">
              <p><strong>Credits Earned:</strong> {record.earnedCredits}</p>
              <p><strong>GPA:</strong> {record.GPA}</p>
              <p><strong>CGPA:</strong> {record.CGPA}</p>
              <p><strong>Academic Standing:</strong> {record.academicStanding}</p>
              <p><strong>Approval Status:</strong> Released</p>
            </div>
            <div className="result-signature-row">
              <span>
                Registrar Approval:{" "}
                {record.finalizedBy?.name || record.releasedBy?.name || "Approved"}
              </span>
              <span>Date Released: {record.releasedAt ? new Date(record.releasedAt).toLocaleDateString() : "N/A"}</span>
            </div>
            <p className="result-sheet-footer">
              Generated by UniPortal — examination prototype for institutional
              review.
            </p>
            <div className="print-hide result-actions">
              <Button onClick={() => window.print()}>Print Result Sheet</Button>
            </div>
          </section>
        ))
      )}
    </div>
  );
}

function formatLabel(value = "") {
  return value
    .replace(/-/g, " ")
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
